a = input ("Digite algo: ")
print ('O tipo primitivo deste valor é', type (a))
print ('So tem espaços?',a.isspace())
print ('É um numero?', a.isnumeric())
print ('É alfabetico?', a.isalpha())
print ('É Alfaeunumerico ?',a.isalnum())
print (' esta em letra maiuscula?',a.isupper())
print ('esta em minusculo?',a.islower())
print ('Esta capitalizada?',a.istitle())
